INCLUDE(CheckIncludeFile)

find_path (PETSC_DIR include/petsc.h
  HINTS ENV PETSC_DIR
  PATHS
  /usr/lib/petsc 		#Debian
  $ENV{HOME}/petsc
  DOC "PETSc Directory")

SET(PETSC_INCLUDE_DIR "${PETSC_DIR}/include/")
CHECK_INCLUDE_FILE( ${PETSC_INCLUDE_DIR}/petsc.h HAVE_PETSC_H )
FIND_LIBRARY(PETSC_LIB_PETSC petsc )
SET(PETSC_LIBRARIES ${PETSC_LIB_PETSC} CACHE STRING "PETSc libraries" FORCE)
if (HAVE_PETSC_H AND PETSC_DIR AND PETSC_LIBRARIES )
  set(HAVE_PETSC 1)
  set(PETSC_FOUND ON)
endif()
set(PETSC_INCLUDES ${PETSC_INCLUDE_DIR} CACHE STRING "PETSc include path" FORCE)
MARK_AS_ADVANCED( PETSC_DIR PETSC_LIB_PETSC PETSC_INCLUDES PETSC_LIBRARIES )
